
package xy.reflect.ui;

import java.util.Map;

import xy.reflect.ui.info.app.IApplicationInfo;
import xy.reflect.ui.info.custom.InfoCustomizations;
import xy.reflect.ui.info.field.IFieldInfo;
import xy.reflect.ui.info.method.IMethodInfo;
import xy.reflect.ui.info.parameter.IParameterInfo;
import xy.reflect.ui.info.type.ITypeInfo;
import xy.reflect.ui.info.type.factory.IInfoProxyFactory;
import xy.reflect.ui.info.type.factory.InfoCustomizationsFactory;
import xy.reflect.ui.info.type.factory.InfoProxyFactory;
import xy.reflect.ui.info.type.source.ITypeInfoSource;
import xy.reflect.ui.info.type.source.SpecificitiesIdentifier;
import xy.reflect.ui.util.MiscUtils;
import xy.reflect.ui.util.ReflectionUIError;

/**
 * This is a subclass of {@link ReflectionUI} that adapts its introspection
 * mechanics according to the given {@link InfoCustomizations} instance.
 * 
 * It uses in order the proxy factories returned by
 * {@link #getInfoCustomizationsSetupFactory()},
 * {@link #getBeforeInfoCustomizationsFactory()}, @{@link #getInfoCustomizationsFactory()}
 * and {@link #getAfterInfoCustomizationsFactory()}.
 * 
 * @author olitank
 *
 */
public class CustomizedUI extends ReflectionUI {

	protected static CustomizedUI defaultInstance;

	protected InfoCustomizations infoCustomizations;
	protected Map<ITypeInfo, ITypeInfo> customizedTypeCache = createCustomizedTypeCache();

	private IInfoProxyFactory infoCustomizationsSetupFactory;
	private IInfoProxyFactory beforeInfoCustomizationsFactory;
	private IInfoProxyFactory infoCustomizationsFactory;
	private IInfoProxyFactory afterInfoCustomizationsFactory;

	/**
	 * @return the default instance of this class. This instance is constructed with
	 *         the {@link InfoCustomizations#getDefault()} return value.
	 */
	public static CustomizedUI getDefault() {
		if (defaultInstance == null) {
			defaultInstance = new CustomizedUI(InfoCustomizations.getDefault());
		}
		return defaultInstance;
	}

	/**
	 * Constructs an instance of this class that will use the given customizations.
	 * 
	 * @param infoCustomizations The abstract UI model customizations specification
	 *                           object.
	 */
	public CustomizedUI(InfoCustomizations infoCustomizations) {
		this.infoCustomizations = infoCustomizations;
	}

	/**
	 * Constructs an instance of this class with empty customizations.
	 */
	public CustomizedUI() {
		this(new InfoCustomizations());
	}

	/**
	 * @return the abstract UI model customizations specification.
	 */
	public InfoCustomizations getInfoCustomizations() {
		return infoCustomizations;
	}

	protected Map<ITypeInfo, ITypeInfo> createCustomizedTypeCache() {
		return MiscUtils.newStandardCache(true);
	}

	/**
	 * @return the cache that maps {@link ITypeInfo} base instances to
	 *         {@link ITypeInfo} final instances generated by the customization
	 *         process. Its access should be synchronized on the monitor returned by
	 *         {@link #getTypeCacheMutex()}.
	 */
	public Map<ITypeInfo, ITypeInfo> getCustomizedTypeCache() {
		return customizedTypeCache;
	}

	@Override
	public ITypeInfo getTypeInfo(ITypeInfoSource typeSource) {
		ITypeInfo result = super.getTypeInfo(typeSource);
		synchronized (getTypeCacheMutex()) {
			ITypeInfo customizedTypesCacheKey = result;
			ITypeInfo cachedResult = customizedTypeCache.get(customizedTypesCacheKey);
			if (cachedResult != null) {
				result = cachedResult;
			} else {
				result = getInfoCustomizationsSetupFactory().wrapTypeInfo(result);
				result = getBeforeInfoCustomizationsFactory().wrapTypeInfo(result);
				result = getInfoCustomizationsFactory().wrapTypeInfo(result);
				result = getAfterInfoCustomizationsFactory().wrapTypeInfo(result);
				customizedTypeCache.put(customizedTypesCacheKey, result);
			}
		}
		return result;
	}

	@Override
	public IApplicationInfo getApplicationInfo() {
		IApplicationInfo result = super.getApplicationInfo();
		result = getInfoCustomizationsSetupFactory().wrapApplicationInfo(result);
		result = getBeforeInfoCustomizationsFactory().wrapApplicationInfo(result);
		result = getInfoCustomizationsFactory().wrapApplicationInfo(result);
		result = getAfterInfoCustomizationsFactory().wrapApplicationInfo(result);
		return result;
	}

	/**
	 * @return the UI model proxy factory that will be used to customize every UI
	 *         model.
	 */
	public final IInfoProxyFactory getInfoCustomizationsFactory() {
		if (infoCustomizationsFactory == null) {
			infoCustomizationsFactory = createInfoCustomizationsFactory();
		}
		return infoCustomizationsFactory;
	}

	/**
	 * @return the UI model proxy factory that will be used to prepare every UI
	 *         model for customizations.
	 */
	public final IInfoProxyFactory getInfoCustomizationsSetupFactory() {
		if (infoCustomizationsSetupFactory == null) {
			infoCustomizationsSetupFactory = createInfoCustomizationsSetupFactory();
		}
		return infoCustomizationsSetupFactory;
	}

	/**
	 * @return an abstract UI model proxy factory that will be used to eventually
	 *         adapt some type/application information before customizations are
	 *         applied.
	 */
	public final IInfoProxyFactory getBeforeInfoCustomizationsFactory() {
		if (beforeInfoCustomizationsFactory == null) {
			beforeInfoCustomizationsFactory = createBeforeInfoCustomizationsFactory();
		}
		return beforeInfoCustomizationsFactory;
	}

	/**
	 * @return an abstract UI model proxy factory that will be used to eventually
	 *         adapt some type/application information after customizations are
	 *         applied.
	 */
	public final IInfoProxyFactory getAfterInfoCustomizationsFactory() {
		if (afterInfoCustomizationsFactory == null) {
			afterInfoCustomizationsFactory = createAfterInfoCustomizationsFactory();
		}
		return afterInfoCustomizationsFactory;
	}

	protected IInfoProxyFactory createInfoCustomizationsFactory() {
		return new InfoCustomizationsFactory(this) {

			@Override
			public String getIdentifier() {
				return "CustomizationsFactory [of=" + CustomizedUI.this.toString() + "]";
			}

			@Override
			protected IInfoProxyFactory getInfoCustomizationsSetupFactory() {
				return CustomizedUI.this.getInfoCustomizationsSetupFactory();
			}

			@Override
			protected InfoCustomizations accessInfoCustomizations() {
				return CustomizedUI.this.infoCustomizations;
			}

		};
	}

	protected IInfoProxyFactory createInfoCustomizationsSetupFactory() {
		return new InfoProxyFactory() {

			@Override
			public String getIdentifier() {
				return "CustomizationsSetupFactory [of=" + CustomizedUI.this.toString() + "]";
			}

			@Override
			protected ITypeInfo getType(IParameterInfo param, IMethodInfo method, ITypeInfo objectType) {
				ITypeInfo result = param.getType();
				ITypeInfoSource source = result.getSource();
				if (source.getSpecificitiesIdentifier() != null) {
					throw new ReflectionUIError(
							"Invalid parameter type info: unexpected source specificities identifier: "
									+ source.getSpecificitiesIdentifier() + ", null value expected" + "\n"
									+ "parameter=" + param.getName() + ", method=" + method.getSignature()
									+ ", objectType=" + objectType.getName() + ", typeInfoSource=" + source);
				}
				return result;
			}

			@Override
			protected ITypeInfo getType(IFieldInfo field, ITypeInfo objectType) {
				ITypeInfo result = field.getType();
				ITypeInfoSource source = result.getSource();
				SpecificitiesIdentifier expectedSpecificitiesIdentifier = new SpecificitiesIdentifier(
						objectType.getName(), field.getName());
				if (!expectedSpecificitiesIdentifier.equals(source.getSpecificitiesIdentifier())) {
					throw new ReflectionUIError("Invalid field type info: unexpected source specificities identifier: "
							+ source.getSpecificitiesIdentifier() + ", expected: " + expectedSpecificitiesIdentifier
							+ "\n" + "typeInfoSource=" + source);
				}
				return result;
			}

			@Override
			protected ITypeInfo getReturnValueType(IMethodInfo method, ITypeInfo objectType) {
				ITypeInfo result = method.getReturnValueType();
				if (result == null) {
					return null;
				}
				ITypeInfoSource source = result.getSource();
				if (source.getSpecificitiesIdentifier() != null) {
					throw new ReflectionUIError("Invalid method type info: unexpected source specificities identifier: "
							+ source.getSpecificitiesIdentifier() + ", null value expected" + "\n" + "method="
							+ method.getName() + ", objectType=" + objectType.getName() + ", typeInfoSource=" + source);
				}
				return result;
			}

		};
	}

	protected IInfoProxyFactory createBeforeInfoCustomizationsFactory() {
		return IInfoProxyFactory.NULL_INFO_PROXY_FACTORY;
	}

	protected IInfoProxyFactory createAfterInfoCustomizationsFactory() {
		return IInfoProxyFactory.NULL_INFO_PROXY_FACTORY;
	}

	@Override
	public String toString() {
		if (this == defaultInstance) {
			return "CustomizedUI.DEFAULT";
		} else {
			return super.toString();
		}
	}

}
