/*******************************************************************************
 * Copyright (C) 2018 OTK Software
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 * 
 * The license allows developers and companies to use and integrate a software 
 * component released under the LGPL into their own (even proprietary) software 
 * without being required by the terms of a strong copyleft license to release the 
 * source code of their own components. However, any developer who modifies 
 * an LGPL-covered component is required to make their modified version 
 * available under the same LGPL license. For proprietary software, code under 
 * the LGPL is usually used in the form of a shared library, so that there is a clear 
 * separation between the proprietary and LGPL components.
 * 
 * The GNU Lesser General Public License allows you also to freely redistribute the 
 * libraries under the same license, if you provide the terms of the GNU Lesser 
 * General Public License with them and add the following copyright notice at the 
 * appropriate place (with a link to http://javacollection.net/reflectionui/ web site 
 * when possible).
 ******************************************************************************/
package xy.reflect.ui.control.swing.util;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;

import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicBorders;

import xy.reflect.ui.control.swing.renderer.SwingRenderer;

/**
 * Base class for buttons generated by the {@link SwingRenderer}.
 * 
 * @author olitank
 *
 */
public abstract class AbstractControlButton extends JButton {

	protected static final long serialVersionUID = 1L;

	public abstract String retrieveText();

	public abstract Image retrieveBackgroundImage();

	public abstract Color retrieveBackgroundColor();

	public abstract Color retrieveForegroundColor();

	public abstract Color retrieveBorderColor();

	protected boolean buttonInitialized = false;
	protected Color buttonBackgroundColor;
	protected Color buttonActivatedBackgroundColor;
	protected Color buttonForegroundColor;
	protected Color buttonBorderColor;
	protected Image buttonBackgroundImage;
	protected Image buttonActivatedBackgroundImage;
	protected String buttonText;
	protected String buttonToolTipText;
	protected Icon buttonIcon;

	public String retrieveToolTipText() {
		return null;
	}

	public Icon retrieveIcon() {
		return null;
	}

	public void updateStyle() {
		buttonBackgroundColor = retrieveBackgroundColor();
		buttonForegroundColor = retrieveForegroundColor();
		buttonBorderColor = retrieveBorderColor();
		buttonBackgroundImage = retrieveBackgroundImage();
		buttonActivatedBackgroundColor = (buttonBackgroundColor == null) ? null
				: SwingRendererUtils.addColorActivationEffect(buttonBackgroundColor);
		buttonActivatedBackgroundImage = (buttonBackgroundImage == null) ? null
				: SwingRendererUtils.addImageActivationEffect(buttonBackgroundImage);
		buttonText = retrieveText();
		buttonToolTipText = retrieveToolTipText();
		buttonIcon = retrieveIcon();

		setText(buttonText);
		if ((buttonToolTipText != null) && (buttonToolTipText.length() > 0)) {
			SwingRendererUtils.setMultilineToolTipText(this, buttonToolTipText);
		} else {
			setToolTipText(null);
		}
		setIcon(buttonIcon);
		if (buttonBackgroundColor != null) {
			setBackground(buttonBackgroundColor);
		} else {
			setBackground(new JButton().getBackground());
		}
		if (buttonForegroundColor != null) {
			setForeground(buttonForegroundColor);
		} else {
			setForeground(new JButton().getForeground());
		}
		if (buttonBorderColor != null) {
			setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(buttonBorderColor),
					new BasicBorders.MarginBorder()));
		} else {
			setBorder(new JButton().getBorder());
		}
		if ((buttonBackgroundImage != null) || (buttonBackgroundColor != null)) {
			setContentAreaFilled(false);
		} else {
			setContentAreaFilled(true);
		}
		if (buttonBackgroundImage != null) {
			setBorderPainted(false);
		} else {
			setBorderPainted(true);
		}
	}

	@Override
	public void addNotify() {
		if (!buttonInitialized) {
			updateStyle();
			buttonInitialized = true;
		}
		super.addNotify();
	}

	@Override
	protected void paintComponent(Graphics g) {
		if (buttonBackgroundImage != null) {
			Runnable paintAction = new Runnable() {
				@Override
				public void run() {
					if (getModel().isArmed()) {
						g.drawImage(buttonActivatedBackgroundImage, 0, 0, getWidth(), getHeight(), null);
					} else {
						g.drawImage(buttonBackgroundImage, 0, 0, getWidth(), getHeight(), null);
					}
				}
			};
			if (g instanceof Graphics2D) {
				SwingRendererUtils.withHighQualityScaling((Graphics2D) g, paintAction);
			} else {
				paintAction.run();
			}
		} else if (buttonBackgroundColor != null) {
			if (getModel().isArmed()) {
				g.setColor(buttonActivatedBackgroundColor);
				g.fillRect(0, 0, getWidth(), getHeight());
			} else if (getModel().isEnabled()) {
				g.setColor(buttonBackgroundColor);
				g.fillRect(0, 0, getWidth(), getHeight());
			}
		}
		super.paintComponent(g);
	}

}
