
package xy.reflect.ui.control.swing.util;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;

import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicBorders;

import xy.reflect.ui.control.swing.renderer.SwingRenderer;

/**
 * Base class for buttons generated by the {@link SwingRenderer}.
 * 
 * @author olitank
 *
 */
public abstract class AbstractControlButton extends JButton {

	protected static final long serialVersionUID = 1L;

	public abstract String retrieveText();

	public abstract Image retrieveBackgroundImage();

	public abstract Color retrieveBackgroundColor();

	public abstract Color retrieveForegroundColor();

	public abstract Color retrieveBorderColor();

	public abstract Font retrieveCustomFont();

	protected boolean styleUpdated = false;
	protected Color mainButtonBackgroundColor;
	protected Color buttonActivatedBackgroundColor;
	protected Color mainButtonForegroundColor;
	protected Color mainButtonBorderColor;
	protected Image buttonBackgroundImage;
	protected String buttonText;
	protected String buttonToolTipText;
	protected Icon buttonIcon;
	protected Font buttonCustomFont;

	public String retrieveToolTipText() {
		return null;
	}

	public Icon retrieveIcon() {
		return null;
	}

	public void updateStyle() {
		mainButtonBackgroundColor = retrieveBackgroundColor();
		mainButtonForegroundColor = retrieveForegroundColor();
		mainButtonBorderColor = retrieveBorderColor();
		buttonBackgroundImage = retrieveBackgroundImage();
		buttonActivatedBackgroundColor = (mainButtonBackgroundColor == null) ? null
				: SwingRendererUtils.addColorActivationEffect(mainButtonBackgroundColor);
		buttonText = retrieveText();
		buttonToolTipText = retrieveToolTipText();
		buttonIcon = retrieveIcon();
		buttonCustomFont = retrieveCustomFont();

		setText(buttonText);
		if ((buttonToolTipText != null) && (buttonToolTipText.length() > 0)) {
			this.setToolTipText(SwingRendererUtils.adaptToolTipTextToMultiline(buttonToolTipText));
		} else {
			setToolTipText(null);
		}
		setIcon(buttonIcon);
		if (mainButtonBackgroundColor != null) {
			setBackground(mainButtonBackgroundColor);
		} else {
			setBackground(new JButton().getBackground());
		}
		if (mainButtonForegroundColor != null) {
			setForeground(mainButtonForegroundColor);
		} else {
			setForeground(new JButton().getForeground());
		}
		if (mainButtonBorderColor != null) {
			setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(mainButtonBorderColor),
					new BasicBorders.MarginBorder()));
		} else {
			setBorder(new JButton().getBorder());
		}
		if ((buttonBackgroundImage != null) || (mainButtonBackgroundColor != null)) {
			setContentAreaFilled(false);
		} else {
			setContentAreaFilled(true);
		}
		if (buttonBackgroundImage != null) {
			setBorderPainted(false);
		} else {
			setBorderPainted(true);
		}
		if (buttonCustomFont != null) {
			setFont(buttonCustomFont.deriveFont(getFont().getStyle(), getFont().getSize()));
		}
		styleUpdated = true;
	}

	@Override
	public void addNotify() {
		if (!styleUpdated) {
			updateStyle();
		}
		super.addNotify();
	}

	@Override
	protected void paintComponent(Graphics g) {
		if (buttonBackgroundImage != null) {
			Runnable paintAction = new Runnable() {
				@Override
				public void run() {
					if (getModel().isArmed()) {
						g.drawImage(SwingRendererUtils.addImageActivationEffect(buttonBackgroundImage), 0, 0,
								getWidth(), getHeight(), null);
					} else {
						g.drawImage(buttonBackgroundImage, 0, 0, getWidth(), getHeight(), null);
					}
				}
			};
			if (g instanceof Graphics2D) {
				SwingRendererUtils.withHighQualityScaling((Graphics2D) g, paintAction);
			} else {
				paintAction.run();
			}
		} else if (mainButtonBackgroundColor != null) {
			if (getModel().isArmed()) {
				g.setColor(buttonActivatedBackgroundColor);
				g.fillRect(0, 0, getWidth(), getHeight());
			} else if (getModel().isEnabled()) {
				g.setColor(mainButtonBackgroundColor);
				g.fillRect(0, 0, getWidth(), getHeight());
			}
		}
		super.paintComponent(g);
	}

}
